# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 900)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabs = QtWidgets.QTabWidget(self.centralwidget)
        self.tabs.setObjectName("tabs")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1261, 171))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4, 0, QtCore.Qt.AlignHCenter)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setVerticalSpacing(6)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.fileBox = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.fileBox.setObjectName("fileBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.fileBox)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.vizSet_box = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.vizSet_box.setObjectName("vizSet_box")
        self.vizSet_box.addItem("")
        self.vizSet_box.addItem("")
        self.vizSet_box.addItem("")
        self.vizSet_box.addItem("")
        self.vizSet_box.addItem("")
        self.vizSet_box.addItem("")
        self.vizSet_box.addItem("")
        self.vizSet_box.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.vizSet_box)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.cutoff_box = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.cutoff_box.setMinimum(0.01)
        self.cutoff_box.setMaximum(24.99)
        self.cutoff_box.setSingleStep(0.01)
        self.cutoff_box.setProperty("value", 2.0)
        self.cutoff_box.setObjectName("cutoff_box")
        self.horizontalLayout_3.addWidget(self.cutoff_box)
        self.linfilBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.linfilBox.setObjectName("linfilBox")
        self.horizontalLayout_3.addWidget(self.linfilBox)
        self.cutoff_angBox = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.cutoff_angBox.setMinimum(0.01)
        self.cutoff_angBox.setMaximum(24.99)
        self.cutoff_angBox.setSingleStep(0.01)
        self.cutoff_angBox.setProperty("value", 2.0)
        self.cutoff_angBox.setObjectName("cutoff_angBox")
        self.horizontalLayout_3.addWidget(self.cutoff_angBox)
        self.angfilBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.angfilBox.setObjectName("angfilBox")
        self.horizontalLayout_3.addWidget(self.angfilBox)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout_3)
        self.btn_viz = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_viz.setEnabled(True)
        self.btn_viz.setObjectName("btn_viz")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.btn_viz)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.mplwindow = QtWidgets.QWidget(self.tab)
        self.mplwindow.setGeometry(QtCore.QRect(0, 170, 1261, 671))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mplwindow.sizePolicy().hasHeightForWidth())
        self.mplwindow.setSizePolicy(sizePolicy)
        self.mplwindow.setObjectName("mplwindow")
        self.mplvl = QtWidgets.QVBoxLayout(self.mplwindow)
        self.mplvl.setContentsMargins(0, 0, 0, 0)
        self.mplvl.setObjectName("mplvl")
        self.tabs.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.widget = QtWidgets.QWidget(self.tab_2)
        self.widget.setGeometry(QtCore.QRect(10, 0, 1241, 841))
        self.widget.setObjectName("widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_8 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_3.addWidget(self.label_8, 0, QtCore.Qt.AlignHCenter)
        self.terminal = QtWidgets.QListWidget(self.widget)
        self.terminal.setObjectName("terminal")
        self.verticalLayout_3.addWidget(self.terminal)
        self.epoch_progress = QtWidgets.QProgressBar(self.widget)
        self.epoch_progress.setStyleSheet("QProgressBar {\n"
"border: 2px solid grey;\n"
"border-radius: 5px;\n"
"background-color: #FFFFFF;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"background-color: #575757;\n"
"}")
        self.epoch_progress.setMinimum(0)
        self.epoch_progress.setProperty("value", 0)
        self.epoch_progress.setObjectName("epoch_progress")
        self.verticalLayout_3.addWidget(self.epoch_progress)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.train_box = QtWidgets.QComboBox(self.widget)
        self.train_box.setObjectName("train_box")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.train_box)
        self.label_11 = QtWidgets.QLabel(self.widget)
        self.label_11.setObjectName("label_11")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.modelBox = QtWidgets.QComboBox(self.widget)
        self.modelBox.setObjectName("modelBox")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.modelBox)
        self.verticalLayout_3.addLayout(self.formLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_15 = QtWidgets.QLabel(self.widget)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_4.addWidget(self.label_15)
        self.epoch_box = QtWidgets.QSpinBox(self.widget)
        self.epoch_box.setMaximum(999)
        self.epoch_box.setProperty("value", 2)
        self.epoch_box.setObjectName("epoch_box")
        self.horizontalLayout_4.addWidget(self.epoch_box)
        self.label_16 = QtWidgets.QLabel(self.widget)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_4.addWidget(self.label_16)
        self.batch_box = QtWidgets.QSpinBox(self.widget)
        self.batch_box.setMaximum(9999)
        self.batch_box.setProperty("value", 64)
        self.batch_box.setObjectName("batch_box")
        self.horizontalLayout_4.addWidget(self.batch_box)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_train = QtWidgets.QPushButton(self.widget)
        self.btn_train.setObjectName("btn_train")
        self.horizontalLayout.addWidget(self.btn_train)
        self.btn_model = QtWidgets.QPushButton(self.widget)
        self.btn_model.setObjectName("btn_model")
        self.horizontalLayout.addWidget(self.btn_model)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.tabs.addTab(self.tab_2, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.tab_4)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 1261, 171))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_6.addWidget(self.label_3, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.synthFile_line = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.synthFile_line.setObjectName("synthFile_line")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.synthFile_line)
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_7.setObjectName("label_7")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.synthOption_box = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.synthOption_box.setObjectName("synthOption_box")
        self.synthOption_box.addItem("")
        self.synthOption_box.addItem("")
        self.synthOption_box.addItem("")
        self.synthOption_box.addItem("")
        self.synthOption_box.addItem("")
        self.synthOption_box.addItem("")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.synthOption_box)
        self.btn_gen = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.btn_gen.setObjectName("btn_gen")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.btn_gen)
        self.verticalLayout_6.addLayout(self.formLayout_4)
        self.synth_progress = QtWidgets.QProgressBar(self.tab_4)
        self.synth_progress.setGeometry(QtCore.QRect(20, 180, 1221, 51))
        self.synth_progress.setStyleSheet("QProgressBar {\n"
"border: 2px solid grey;\n"
"border-radius: 5px;\n"
"background-color: #FFFFFF;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"background-color: #575757;\n"
"}")
        self.synth_progress.setProperty("value", 0)
        self.synth_progress.setOrientation(QtCore.Qt.Horizontal)
        self.synth_progress.setObjectName("synth_progress")
        self.synth_terminal = QtWidgets.QListWidget(self.tab_4)
        self.synth_terminal.setGeometry(QtCore.QRect(20, 270, 1221, 331))
        self.synth_terminal.setObjectName("synth_terminal")
        self.tabs.addTab(self.tab_4, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_10 = QtWidgets.QLabel(self.tab_3)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_5.addWidget(self.label_10, 0, QtCore.Qt.AlignHCenter)
        self.progressBar = QtWidgets.QProgressBar(self.tab_3)
        self.progressBar.setStyleSheet("QProgressBar {\n"
"border: 2px solid grey;\n"
"border-radius: 5px;\n"
"background-color: #FFFFFF;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"background-color: #575757;\n"
"}")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_5.addWidget(self.progressBar)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_9 = QtWidgets.QLabel(self.tab_3)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.line_fname = QtWidgets.QLineEdit(self.tab_3)
        self.line_fname.setObjectName("line_fname")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.line_fname)
        self.label_12 = QtWidgets.QLabel(self.tab_3)
        self.label_12.setObjectName("label_12")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.line_imutopic = QtWidgets.QLineEdit(self.tab_3)
        self.line_imutopic.setObjectName("line_imutopic")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.line_imutopic)
        self.label_13 = QtWidgets.QLabel(self.tab_3)
        self.label_13.setObjectName("label_13")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.line_cmdtopic = QtWidgets.QLineEdit(self.tab_3)
        self.line_cmdtopic.setObjectName("line_cmdtopic")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.line_cmdtopic)
        self.label_14 = QtWidgets.QLabel(self.tab_3)
        self.label_14.setObjectName("label_14")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.runtime_box = QtWidgets.QSpinBox(self.tab_3)
        self.runtime_box.setMaximum(1200)
        self.runtime_box.setSingleStep(10)
        self.runtime_box.setProperty("value", 30)
        self.runtime_box.setObjectName("runtime_box")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.runtime_box)
        self.btn_start = QtWidgets.QPushButton(self.tab_3)
        self.btn_start.setObjectName("btn_start")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.btn_start)
        self.verticalLayout_5.addLayout(self.formLayout_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.tabs.addTab(self.tab_3, "")
        self.verticalLayout.addWidget(self.tabs)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabs.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "IMU Analyzer"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">IMU Data Visualization</span></p></body></html>"))
        self.label.setText(_translate("MainWindow", "File"))
        self.label_5.setText(_translate("MainWindow", "Visualizer Setting"))
        self.vizSet_box.setItemText(0, _translate("MainWindow", "Linear"))
        self.vizSet_box.setItemText(1, _translate("MainWindow", "Angular"))
        self.vizSet_box.setItemText(2, _translate("MainWindow", "Time"))
        self.vizSet_box.setItemText(3, _translate("MainWindow", "All"))
        self.vizSet_box.setItemText(4, _translate("MainWindow", "FFT"))
        self.vizSet_box.setItemText(5, _translate("MainWindow", "X"))
        self.vizSet_box.setItemText(6, _translate("MainWindow", "Y"))
        self.vizSet_box.setItemText(7, _translate("MainWindow", "Z"))
        self.linfilBox.setText(_translate("MainWindow", "lin_filter"))
        self.angfilBox.setText(_translate("MainWindow", "ang_filter"))
        self.btn_viz.setText(_translate("MainWindow", "Visualize Data"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab), _translate("MainWindow", "IMU Analyzer"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" text-decoration: underline;\">LSTM Training and Visualization</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "Datafile"))
        self.label_11.setText(_translate("MainWindow", "Modelfile"))
        self.label_15.setText(_translate("MainWindow", "Epochs"))
        self.label_16.setText(_translate("MainWindow", "Batch Size"))
        self.btn_train.setText(_translate("MainWindow", "Training"))
        self.btn_model.setText(_translate("MainWindow", "Load Model"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_2), _translate("MainWindow", "LSTM Analyzer"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; font-style:italic; text-decoration: underline;\">Data Synthesis</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "Filename"))
        self.label_7.setText(_translate("MainWindow", "Synthtime [s]"))
        self.synthOption_box.setItemText(0, _translate("MainWindow", "7200"))
        self.synthOption_box.setItemText(1, _translate("MainWindow", "6400"))
        self.synthOption_box.setItemText(2, _translate("MainWindow", "4000"))
        self.synthOption_box.setItemText(3, _translate("MainWindow", "9600"))
        self.synthOption_box.setItemText(4, _translate("MainWindow", "16000"))
        self.synthOption_box.setItemText(5, _translate("MainWindow", "300"))
        self.btn_gen.setText(_translate("MainWindow", "Generate and Plot"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_4), _translate("MainWindow", "Synthetic Data"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:22pt; font-weight:600; font-style:italic; text-decoration: underline;\">Data Collection</span></p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "Filename"))
        self.line_fname.setText(_translate("MainWindow", "lab001"))
        self.label_12.setText(_translate("MainWindow", "IMU Topic"))
        self.line_imutopic.setText(_translate("MainWindow", "/imu"))
        self.label_13.setText(_translate("MainWindow", "CMD Topic"))
        self.line_cmdtopic.setText(_translate("MainWindow", "/mobile_base/commands/velocity"))
        self.label_14.setText(_translate("MainWindow", "Run-Time [s]"))
        self.btn_start.setText(_translate("MainWindow", "Start Stream"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_3), _translate("MainWindow", "Data Collector"))


